wordpress:
  image: wordpress
  volumes:
  - ./backend:/var/www/html
  # - ./files/wp-config.php:/var/www/html/wp-config.php
  # - ./files/wp-content:/var/www/html/wp-content
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
wordpress_db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: password
  volumes:
    - ./database/.db:/var/lib/mysql
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8081:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: password